server:
  port: 8501

spring:
  profiles:
    # 环境配置
#    active: dev
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:9090
